### ISSUE TITLE
Ordered lists don't show their numbers

### ISSUE THREAD

**Issue by gxjansen** [spryker-community/spryker-community.github.io#32]
In docs/starlight

**Comment by fsmeier** [comment]
![Screenshot 2024-11-04 at 17 19 59](https://github.com/user-attachments/assets/25f5b168-f9ad-4e38-b41f-7b1c41ab884e)

So in Starlight initially you need to use the component "Steps" to show an ordered list (as shown in the picture). I "fixed" it by introducing styling for an ordered list without using that component.
