### ISSUE TITLE
Use same header for main landing page and docs/resources

### ISSUE THREAD

**Issue by gxjansen** [spryker-community/spryker-community.github.io#49]
The docs/resources section (Starlight) header (src/components/ui/starlight/Head.astro) uses a different navigation element than the main Astro section (src/layouts/MainLayout.astro uses (components/sections/Navbar.astro). The main Astro header needs to be applied to the docs as well AND include the search bar.

Note that both have a light/darkmode switch, but each is different.

**Comment by fsmeier** [comment]
Search is moved to spryker-community/spryker-community.github.io#18
